description = "Embedded Web Server - generator"
long-description = """

EWS is a web server construction kit, designed for embedded
applications using the GNAT Ada compiler.

The project is hosted at https://github.com/simonjwright/ews.

This subproject builds a program (generator) which generates Ada
source code corresponding to a web source directory tree.

"""
name = "generator"
version = "1.11.0"
authors = ["Simon Wright <simon@pushface.org>"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]
project-files = ["ews_generator.gpr"]
tags = ["web", "server", "generator"]
website = "https://github.com/simonjwright/ews"

[[depends-on]]
gnat_native = "*"
